package com.example.service.response;

public enum ServiceMessage {
    ADDED_PRODUCT_ALREADY_IN_ORDER,
    PRODUCT_IS_NOT_IN_ORDER,
    ORDER_SHOULD_NOT_BE_EMPTY,
    ORDER_OWNER_ID_NOT_EQUALS_TO_AUTHORIZED_USER_ID,
    DELIVERYLIST_OWNER_ID_NOT_EQUALS_TO_AUTHORIZED_USER_ID,
    SHOULD_HAS_EXISTING_ID,
    SHOULD_NOT_HAS_ID,
    USER_WITH_THIS_USERNAME_ALREADY_EXIST
}
