
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

#    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_DATABASE:postgres}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:12345}

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false